### PR TITLE
Fixed Korean translations

### PR DESCRIPTION
**Pull request by cherryband**

### CODE REVIEW

**Comment by Deevad** [comment]
In this one, I don't see the Inkscape 0.92 file tag ; did you use a previous version as 0.91 ?
The files looks good to be on renderfarm, but I prefer to have your confirmation :) thank you; and sorry for all those questions about Inkscape. This issues are new and really specific to this month , I'm sure I'll get used to fix this and have a proper renderfarm to auto-fix all version in a month.

**Comment by cherryband** [comment]
This one is done in another computer. It had Elementary OS installed, and the package manager doesn't have 0.92 yet. So I think it's good to go.

**Comment by Deevad** [comment]
Thank you for the confirmation, let's try to render this one :)

**Comment by Deevad** [comment]
It's online @qtwyeuritoiy ! Good job with the font refactoring ; it's look way more appealing this way!
http://www.peppercarrot.com/kr/article241/episode-3-the-secret-ingredients

**Pull request merged**
